import type { Metadata } from "next";
import { Inter, Handlee } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const handlee = Handlee({subsets:["latin"], weight: "400", variable:"--font-handlee"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={handlee.variable}>{children}</body>
    </html>
  );
}
